export const actionTypes = {
  FETCH_MEMBERS_COMPLETED: 'FETCH_MEMBERS_COMPLETED',
  FETCH_MEMBER_BY_ID_COMPLETED: 'FETCH_MEMBER_BY_ID_COMPLETED',
  UPDATE_MEMBER_FIELD: 'UPDATE_MEMBER_FIELD',
  SAVE_MEMBER: 'SAVE_MEMBER',
  SAVE_USER: 'SAVE_URER',
  UPDATE_USER_FIELD: 'UPDATE_USER_FIELD',
  CLEAR_USER: 'CLEAR_USER',
  FETCH_POST_CONF_DATA: 'FETCH_POST_CONF_DATA',
  CHANGE_SLIDER_ITEM: 'CHANGE_SLIDER_ITEM',
  GET_SIDER_ITEM: 'GET_SIDER_ITEM',
  FETCH_POST_CONF_DETAIL: 'FETCH_POST_CONF_DETAIL',
  FETCH_POST_CONF_DETAIL_CLEAR: 'FETCH_POST_CONF_DETAIL_CLEAR',
  DELETE_POST_CONF_DATA_ID: 'DELETE_POST_CONF_DATA_ID'
};
